version: "3.7"

services:
  backend:
    build: ./
    restart: always
    command: gunicorn app.main:app --bind 0.0.0.0:5000 -w 4 -k uvicorn.workers.UvicornWorker
    expose:
      - 5000
    labels: # new
      - "traefik.enable=true"
      - "traefik.http.routers.app-http.rule=Host(`fastapi.localhost`)"
  traefik:
    image: traefik:v2.2
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "$PWD/services/traefik/traefik.dev.toml:/etc/traefik/traefik.toml"
